"""Migracion de tablas #8

Revision ID: 31043b85d7b9
Revises: 9ffb0e2dca16
Create Date: 2025-11-30 16:31:22.249477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31043b85d7b9'
down_revision: Union[str, Sequence[str], None] = '9ffb0e2dca16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
