"""Primera migracion de modelos

Revision ID: 311837f4f1bc
Revises: 
Create Date: 2025-10-11 20:47:20.605027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311837f4f1bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacion',
    sa.Column('id_organizacion', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_organizacion')
    )
    op.create_table('pais',
    sa.Column('id_pais', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_pais')
    )
    op.create_index(op.f('ix_pais_nombre'), 'pais', ['nombre'], unique=False)
    op.create_table('rol',
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('region',
    sa.Column('id_region', sa.UUID(), nullable=False),
    sa.Column('id_pais', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id_pais'], ),
    sa.PrimaryKeyConstraint('id_region')
    )
    op.create_index(op.f('ix_region_nombre'), 'region', ['nombre'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_organizacion', sa.UUID(), nullable=True),
    sa.Column('id_rol', sa.UUID(), nullable=False),
    sa.Column('nombre_1', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nombre_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('apellido_1', sa.VARCHAR(length=50), nullable=False),
    sa.Column('apellido_2', sa.VARCHAR(length=50), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizacion.id_organizacion'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('ciudad',
    sa.Column('id_ciudad', sa.UUID(), nullable=False),
    sa.Column('id_pais', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['region.id_region'], ),
    sa.PrimaryKeyConstraint('id_ciudad')
    )
    op.create_table('evento',
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_inicio', sa.DATETIME(), nullable=False),
    sa.Column('fecha_fin', sa.DATETIME(), nullable=False),
    sa.Column('url_info', sa.VARCHAR(length=100), nullable=True),
    sa.Column('valor', sa.FLOAT(), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_edicion', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('imagen_evento',
    sa.Column('id_imagen', sa.UUID(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('ubicacion',
    sa.Column('id_ubicacion', sa.UUID(), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=False),
    sa.Column('complemento_1', sa.VARCHAR(length=30), nullable=True),
    sa.Column('complemento_2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('latitud', sa.FLOAT(), nullable=False),
    sa.Column('longitud', sa.FLOAT(), nullable=False),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('fecha_crea', sa.DATETIME(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_edita', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_ubicacion')
    )
    op.create_table('eventos_ubicaciones',
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.Column('id_ubicacion', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id_ubicacion'], ),
    sa.PrimaryKeyConstraint('id_evento', 'id_ubicacion')
    )
    op.create_table('organizaciones_eventos',
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.Column('id_organizacion', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizacion.id_organizacion'], ),
    sa.PrimaryKeyConstraint('id_evento', 'id_organizacion')
    )
    op.create_table('punto_interes',
    sa.Column('id_punto_interes', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('id_ubicacion', sa.UUID(), nullable=False),
    sa.Column('url_info', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('fecha_crea', sa.DateTime(), nullable=False),
    sa.Column('id_usuario_edita', sa.UUID(), nullable=True),
    sa.Column('fecha_edita', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_ubicacion'], ['ubicacion.id_ubicacion'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_edita'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_punto_interes')
    )
    op.create_table('imagen_PI',
    sa.Column('id_imagen', sa.UUID(), nullable=False),
    sa.Column('id_punto_interes', sa.UUID(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_usuario_crea', sa.UUID(), nullable=False),
    sa.Column('fecha_crea', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_punto_interes'], ['punto_interes.id_punto_interes'], ),
    sa.ForeignKeyConstraint(['id_usuario_crea'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagen_PI')
    op.drop_table('punto_interes')
    op.drop_table('organizaciones_eventos')
    op.drop_table('eventos_ubicaciones')
    op.drop_table('ubicacion')
    op.drop_table('imagen_evento')
    op.drop_table('evento')
    op.drop_table('ciudad')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_region_nombre'), table_name='region')
    op.drop_table('region')
    op.drop_table('rol')
    op.drop_index(op.f('ix_pais_nombre'), table_name='pais')
    op.drop_table('pais')
    op.drop_table('organizacion')
    # ### end Alembic commands ###
