"""Migracion de tablas #2

Revision ID: 33fdd2674abe
Revises: da48c081de78
Create Date: 2025-11-30 15:20:42.725763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fdd2674abe'
down_revision: Union[str, Sequence[str], None] = 'da48c081de78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pais_nombre'), table_name='pais', schema='e_spot_schema')
    op.create_index(op.f('ix_e_spot_schema_pais_nombre'), 'pais', ['nombre'], unique=False, schema='e_spot_schema')
    op.drop_index(op.f('ix_region_nombre'), table_name='region', schema='e_spot_schema')
    op.create_index(op.f('ix_e_spot_schema_region_nombre'), 'region', ['nombre'], unique=False, schema='e_spot_schema')
    op.add_column('ubicacion', sa.Column('id_ciudad', sa.UUID(), nullable=False), schema='e_spot_schema')
    op.create_foreign_key(None, 'ubicacion', 'ciudad', ['id_ciudad'], ['id_ciudad'], source_schema='e_spot_schema', referent_schema='e_spot_schema')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario', schema='e_spot_schema')
    op.create_index(op.f('ix_e_spot_schema_usuario_correo'), 'usuario', ['correo'], unique=True, schema='e_spot_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_e_spot_schema_usuario_correo'), table_name='usuario', schema='e_spot_schema')
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True, schema='e_spot_schema')
    op.drop_constraint(None, 'ubicacion', schema='e_spot_schema', type_='foreignkey')
    op.drop_column('ubicacion', 'id_ciudad', schema='e_spot_schema')
    op.drop_index(op.f('ix_e_spot_schema_region_nombre'), table_name='region', schema='e_spot_schema')
    op.create_index(op.f('ix_region_nombre'), 'region', ['nombre'], unique=False, schema='e_spot_schema')
    op.drop_index(op.f('ix_e_spot_schema_pais_nombre'), table_name='pais', schema='e_spot_schema')
    op.create_index(op.f('ix_pais_nombre'), 'pais', ['nombre'], unique=False, schema='e_spot_schema')
    # ### end Alembic commands ###
