"""Migracion de tablas #5

Revision ID: 67e5bd9541d2
Revises: 1f66e5b40716
Create Date: 2025-11-30 15:39:40.565963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e5bd9541d2'
down_revision: Union[str, Sequence[str], None] = '1f66e5b40716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
