"""Migracion de tablas #4

Revision ID: 77a2769faafb
Revises: 53116231bcdb
Create Date: 2025-11-30 15:31:43.964906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77a2769faafb'
down_revision: Union[str, Sequence[str], None] = '53116231bcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imagen_evento', 'id_evento',
               existing_type=sa.UUID(),
               nullable=True,
               schema='e_spot_schema')
    op.create_foreign_key(None, 'imagen_evento', 'evento', ['id_evento'], ['id_evento'], source_schema='e_spot_schema', referent_schema='e_spot_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imagen_evento', schema='e_spot_schema', type_='foreignkey')
    op.alter_column('imagen_evento', 'id_evento',
               existing_type=sa.UUID(),
               nullable=False,
               schema='e_spot_schema')
    # ### end Alembic commands ###
