"""Migracion de tablas #8

Revision ID: 9ffb0e2dca16
Revises: c90bca2ddf0a
Create Date: 2025-11-30 16:25:48.759280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffb0e2dca16'
down_revision: Union[str, Sequence[str], None] = 'c90bca2ddf0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte',
    sa.Column('id_reporte', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.TEXT(), nullable=False),
    sa.Column('id_evento', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['e_spot_schema.evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_reporte'),
    schema='e_spot_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte', schema='e_spot_schema')
    # ### end Alembic commands ###
