"""Migracion de tablas #6

Revision ID: c124f9a9a1d6
Revises: 2fcced11780f
Create Date: 2025-11-30 15:46:30.797838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c124f9a9a1d6'
down_revision: Union[str, Sequence[str], None] = '2fcced11780f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
