"""Migracion de tablas #8

Revision ID: c90bca2ddf0a
Revises: 4e0d333cf7bc
Create Date: 2025-11-30 16:15:27.388251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90bca2ddf0a'
down_revision: Union[str, Sequence[str], None] = '4e0d333cf7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
